# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39e08d0bd90ee77313d3e7e2f2018963709162412e0a5471325b7d6857457e861bf2bae201d818cb6da1c3dd1438c1cd0417c1dfa9006941b149c8625467f527

test:
  secret_key_base: f71105165f0d928cd3b82e1fddca8a13a6f60cfd097080540bd0aefc8076f33ab9af1545a27648e67c324a27bb754cd1b61d01de5f9ba4ccb5d257817863e61a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
